
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
security:
  oauth2:
    client:
      client-id: demo
      client-secret: demoSecret
      user-authorization-uri: http://127.0.0.1:6060/oauth/authorize
      access-token-uri: http://127.0.0.1:6060/oauth/token
      scope: application
    resource:
      jwt:
        key-uri: http://127.0.0.1:6060/oauth/token_key
spring:
  application:
    name: sso-client-demo
  profiles:
    active: dev
  redis:
    remote: true
    host: 127.0.0.1
    port: 6379
    password:
urls:
  anon:
    - /demo/**
logging.level.org.springframework.security: DEBUG
server:
  port: 40351